# Generated by Django 3.2.5 on 2022-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('COMPLETED', 'COMPLETED')], default='CREATED', max_length=30),
        ),
    ]
